- name: Manage Docker containers
  hosts: contest_server
  become: true
  tasks:
    - name: Pull the Docker image
      docker_image:
        name: timepresent95/contest-be
        tag: latest
        source: pull

    - name: Remove the existing contest_be container if running
      docker_container:
        name: contest_be
        state: absent

    - name: Run Docker container
      docker_container:
        name: contest_be
        image: timepresent95/contest-be:latest
        state: started
        ports:
          - "5000:5000"
        restart_policy: always
