- name: Manage Docker containers
  hosts: contest_web
  become: true
  tasks:
    - name: Pull the Docker image
      docker_image:
        name: timepresent95/contest-fe
        tag: latest
        source: pull

    - name: Remove the existing contest_fe container if running
      docker_container:
        name: contest_fe
        state: absent

    - name: Run Docker container
      docker_container:
        name: contest_fe
        image: timepresent95/contest-fe:latest
        state: started
        ports:
          - "3000:3000"
        restart_policy: always
